spring:
  application:
    name: RoadMap

  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 10MB # 업로드 가능한 파일의 최대 크기 설정
      max-request-size: 10MB # 한 요청에서 업로드 가능한 전체 파일 용량 제한

# 기본 캐시 설정
  cache:
    type: redis # Redis를 캐시 프로바이더로 사용
    redis:
      time-to-live: 7200000 # 2시간 (밀리초)

server:
  port: 8080

# 파일 업로드 설정
file:
  upload:
    path: uploads/images # 이미지 파일 저장 경로
    base-url: http://localhost:8080 # 이미지 URL 생성을 위한 기본 URL

logging:
  level:
    root: INFO # 전체 로그 레벨을 INFO로 설정
    org.springframework.web: DEBUG # 웹 관련 로깅은 DEBUG 레벨로 설정 (HTTP 요청/응답 등 상세 보기)
    com.shingu.roadmap: DEBUG # 애플리케이션 패키지의 로깅 레벨을 DEBUG로 설정
    com.shingu.roadmap.diagnosis.service.DiagnosisStateService: TRACE

springdoc:
  swagger-ui:
    path: /api-docs
    display-request-duration: true # 요청 응답 시간 표시 여부
    operations-sorter: alpha # API 메서드들을 알파벳 순으로 정렬
    tags-sorter: alpha # 태그들을 알파벳 순으로 정렬

management:
  endpoints:
    web:
      exposure:
        include: "*" # Actuator의 모든 엔드포인트를 외부에 노출 (주의: 운영 환경에서는 제한 필요)
  endpoint:
    health:
      show-details: always # `/actuator/health`에서 상세 상태 정보를 항상 보여줌